// <auto-generated />
using System;
using Message.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Message.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20210329212536_Something")]
    partial class Something
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Message.Models.BMessage", b =>
                {
                    b.Property<int>("BMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BMessageId");

                    b.ToTable("BMessages");

                    b.HasData(
                        new
                        {
                            BMessageId = 1,
                            Message = "Matilda",
                            Posted = new DateTime(2021, 3, 29, 16, 25, 35, 952, DateTimeKind.Local).AddTicks(5049)
                        },
                        new
                        {
                            BMessageId = 2,
                            Message = "Rexie",
                            Posted = new DateTime(2021, 3, 29, 16, 25, 35, 952, DateTimeKind.Local).AddTicks(5325)
                        },
                        new
                        {
                            BMessageId = 3,
                            Message = "Matilda",
                            Posted = new DateTime(2021, 3, 29, 16, 25, 35, 952, DateTimeKind.Local).AddTicks(5334)
                        },
                        new
                        {
                            BMessageId = 4,
                            Message = "Pip",
                            Posted = new DateTime(2021, 3, 29, 16, 25, 35, 952, DateTimeKind.Local).AddTicks(5337)
                        },
                        new
                        {
                            BMessageId = 5,
                            Message = "Bartholomew",
                            Posted = new DateTime(2021, 3, 29, 16, 25, 35, 952, DateTimeKind.Local).AddTicks(5339)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
